### ISSUE TITLE
SlackBot : websocket connection closes with SSLException

### ISSUE THREAD

**Issue by ochompsky** [rampatra/jbot#103]
It seems to be totally random - after a few hours or days the bot will just crash.  I'm running a barely modified version of the example bot on a dedicated Ubuntu 16 server doing nothing else.  There isn't much to go on in the logs.  Is there a place to catch this exception and reestablish the connection?

> 2018-06-07 18:36:57.761 DEBUG 1030 --- [ient-SecureIO-2] me.ramswaroop.jbot.core.slack.Bot        : WebSocket closed: StandardWebSocketSession[id=0, uri=null], Close Status: CloseStatus[code=1006, reason=Unexpected Status of SSLEngineResult after an unwrap() operation]

EDIT:  Seems to be the same as #97

**Comment by rampatra** [comment]
Can you try calling the `startWebSocketConnection()` method (added in this [PR](https://github.com/rampatra/jbot/pull/99)) when the connection closes?

**Comment by ochompsky** [comment]
thanks @rampatra i've added it to my code....will run it for a few days and update

**Comment by ochompsky** [comment]
unfortunately the issue persists.  this time i didn't even see an error, the logs just suddenly ended and the program went offline.

**Comment by guikessa** [comment]
I have the same in centOS 7

**Comment by rampatra** [comment]
Yes, currently JBot is deployed in my own personal [DigitalOcean](https://m.do.co/c/eadfbc9d4c64) server. You can even interact with my bot on [Facebook](https://www.facebook.com/jbotframework) (by clicking the send message button). I have deployed my `jbot-example` from this repo. I would suggest using a process manager to keep the application online for a longer time. For example, [supervisord.org](http://supervisord.org) or something similar. I have used the same.

**Comment by Nazar482** [comment]
@rampatra can you fix this freaking issue? bot is going offline in slack all the time.
Slack WS session has been closed
Every freaking time, 3 times a day. Its impossible.

**Comment by ochompsky** [comment]
so as usual the bot crashed again.   i did notice this in the logs this time


> 2018-06-15 14:49:01.399 DEBUG 1008 --- [ient-SecureIO-1] me.ramswaroop.jbot.core.slack.Bot        : WebSocket closed: StandardWebSocketSession[id=4620, uri=null], Close Status: CloseStatus[code=1006, reason=Unexpected Status of SSLEngineResult after an unwrap() operation]
> 2018-06-15 14:49:01.399  INFO 1008 --- [ient-SecureIO-1] o.s.w.s.c.WebSocketConnectionManager     : Starting WebSocketConnectionManager
> 2018-06-15 14:49:01.399  INFO 1008 --- [ient-SecureIO-1] o.s.w.s.c.WebSocketConnectionManager     : Connecting to WebSocket at wss://cerberus-xxxx.lb.slack-msgs.com/websocket/<removed>
> 2018-06-15 14:49:01.468 DEBUG 1008 --- [cTaskExecutor-1] me.ramswaroop.jbot.core.slack.Bot        : WebSocket connected: StandardWebSocketSession[id=4621, uri=null]
> 2018-06-15 14:49:01.469  INFO 1008 --- [cTaskExecutor-1] o.s.w.s.c.WebSocketConnectionManager     : Successfully connected
> 2018-06-15 14:49:01.469 DEBUG 1008 --- [ient-SecureIO-1] me.ramswaroop.jbot.core.slack.Bot        : Response from Slack: {"type":"error","error":{"msg":"Socket URL has expired","code":1,"source":"gs-iad-u7xi"}}
> 2018-06-15 14:49:01.469 DEBUG 1008 --- [ient-SecureIO-1] me.ramswaroop.jbot.core.slack.Bot        : WebSocket closed: StandardWebSocketSession[id=4621, uri=null], Close Status: CloseStatus[code=1006, reason=Unexpected Status of SSLEngineResult after an unwrap() operation]
>   
> 


It did attempt the reconnect but it looks like the URL it's using is no good?

**Comment by rampatra** [comment]
I was reading this answer on [SOF](https://stackoverflow.com/a/25950809/1385441) and I think I can do things to overcome this:
1. Send a ping at regular intervals to keep the connection alive
2. Call startRTM() to get a new socket url and connect to it everytime the connection failed

**Comment by ochompsky** [comment]
thanks for the link, that's a good read.  i do notice that the connection seems to die overnight most of the time, possibly due to inactivity in the slack channel the bot is in.  

i think 2 is probably a better approach because it would also handle other websocket failures.  i will mess around a bit on my end and see if i can get either approach to work.

**Comment by rampatra** [comment]
Look what I just found on Slack documentation. It suggests that if there is no other activity, clients should send a ping every few seconds. https://api.slack.com/rtm (See section "Ping and Pong").

I would soon release a new version of JBot including this feature. Hope this will solve the problem of many.

**Comment by rampatra** [comment]
New version of JBot released which fixes web socket connection issues: https://github.com/rampatra/jbot/releases/tag/jbot-4.1.0
