### ISSUE TITLE
One thread for each user?

### ISSUE THREAD

**Issue by alisenberg** [rampatra/jbot#107]
Hi, is it possible to receive messages from different users in a concurrent way? In my tests I receive every message in the same thread, and that blocks until reply the first message instead of processing messages in parallel.
thanks
Adrian

**Comment by rampatra** [comment]
Hi Adrian,
You need not wait for the first reply to be sent in order to send the next reply. You can send `reply()` asynchronously in a different thread. You can see `PingTask` in `Bot.java` as a "kind of" similar example which sends a ping message every 30 seconds independently of other replies.
