### ISSUE TITLE
How would I configure this to use an http proxy to connect to slack.com?

### ISSUE THREAD

**Issue by HighlanderZ** [rampatra/jbot#108]
How would I configure this to use an http proxy to connect to slack.com?

**Comment by HighlanderZ** [comment]
Adding the following java parameters did the trick
-Dhttps.proxySet=true -Dhttps.proxyHost=xxx -Dhttps.proxyPort=80

**Comment by rampatra** [comment]
Glad you figured it out. I am closing the issue for now.
