### ISSUE TITLE
Conversations in FB bot

### ISSUE THREAD

**Issue by marcin-apzumi** [rampatra/jbot#112]
Hi,

i created a bot with jbot, and everything was working fine until i published my app. Now conversation works strangely e.g. when i start conversation bot reply with all steps in this conversation - not waiting for typing some response or reply  twice with the same answer

Any idea why it's happens?

this is my code:
![image](https://user-images.githubusercontent.com/41676957/43193162-8b9ab76c-8fff-11e8-98f1-6e8c75be1916.png)

and the response is: 
Password:
Password:

**Comment by rampatra** [comment]
Hi, can you please the entire conversation code?

It should be something like:
```java
@Controller(pattern = "(setup meeting)", next = "confirmTiming")
    public void setupMeeting(WebSocketSession session, Event event) {
        startConversation(event, "confirmTiming");   // start conversation
        reply(session, event, "Cool! At what time (ex. 15:30) do you want me to set up the meeting?");
    }

    @Controller(next = "askTimeForMeeting")
    public void confirmTiming(WebSocketSession session, Event event) {
        reply(session, event, "Your meeting is set at " + event.getText() +
                ". Would you like to repeat it tomorrow?");
        nextConversation(event);    // jump to next question in conversation
    }

    @Controller(next = "askWhetherToRepeat")
    public void askTimeForMeeting(WebSocketSession session, Event event) {
        if (event.getText().contains("yes")) {
            reply(session, event, "Okay. Would you like me to set a reminder for you?");
            nextConversation(event);    // jump to next question in conversation  
        } else {
            reply(session, event, "No problem. You can always schedule one with 'setup meeting' command.");
            stopConversation(event);    // stop conversation only if user says no
        }
    }

    @Controller
    public void askWhetherToRepeat(WebSocketSession session, Event event) {
        if (event.getText().contains("yes")) {
            reply(session, event, "Great! I will remind you tomorrow before the meeting.");
        } else {
            reply(session, event, "Okay, don't forget to attend the meeting tomorrow :)");
        }
        stopConversation(event);    // stop conversation
    }
```

**Comment by marcin-apzumi** [comment]
hi,

thanks for Your answer before I wrote to You i paste this code:

![image](https://user-images.githubusercontent.com/41676957/43194461-ac2fd9d2-9002-11e8-9cfe-e4bed3df92a4.png)

and the result is:

![image](https://user-images.githubusercontent.com/41676957/43194479-b962dec4-9002-11e8-9345-98437c5e5109.png)

**Comment by rampatra** [comment]
I don't see any change in the code above from the example, I think maybe somehow you tangled with the conversation states. Can you restart your bot and try, please?

**Comment by marcin-apzumi** [comment]
i found, that facebook send me every message twice - when i handle this everything with conversation is ok. thanks for your help
