### ISSUE TITLE
I cant execute the jbot-example

### ISSUE THREAD

**Issue by joaquingalliano** [rampatra/jbot#124]
When I cloned the repo this doesn't import the imports like me.* and org.* that program use on SlackBot.java class. Is this an issue for the repo? Or is only my issue?

**Comment by rampatra** [comment]
There may be some issue with your IDE. It may not be able to download the maven dependencies properly. I am closing this PR as this seems impertinent to the JBot framework. You can try StackOverflow for this question instead.
