### ISSUE TITLE
Slack: Sending messages too quickly can result in TEXT_PARTIAL_WRITING error

### ISSUE THREAD

**Issue by jbeemster** [rampatra/jbot#125]
It seems that the WebSocket connection does not like it when too many messages are sent at the same time and can result in the following error:

> java.lang.IllegalStateException: The remote endpoint was in state [TEXT_PARTIAL_WRITING] which is an invalid state for called method

This never resolves itself and requires a full reboot of the service to make it work again.  This appears to be partially due to the fact that the ping service running in the background might occasionally conflict with the user called reply function and this concurrency causes an unresolvable exception within the websocket session.

Most suggestions seem to suggest that wrapping the `sendMessage` within a `synchronized` block can fix this issue so the Bot class would need to be restructured slightly to support this.

---

Has anyone else run into this issue or have any suggestions?

**Comment by rampatra** [comment]
@jbeemster would appreciate if you can update/close this ticket if your PR resolved this issue.

**Comment by jbeemster** [comment]
Hey @rampatra its on my todo list to test it all out thoroughly - is it possible to get a SNAPSHOT / RC build pushed to maven?

**Comment by jbeemster** [comment]
Hey @rampatra just checking again if it would be possible to get an RC published of the current master?

**Comment by rampatra** [comment]
@jbeemster yes, I had some issues releasing. Hopefully, nexus repository has fixed my issue. Will update you.

**Comment by rampatra** [comment]
@jbeemster can you pl check maven central and if it doesn't appear within the next 2 hours, I will give it another look. There should probably be no problems. The RC version is `jbot-4.1.2-rc.1`.

**Comment by rampatra** [comment]
It is available on maven central now: https://search.maven.org/artifact/me.ramswaroop.jbot/jbot/4.1.2-rc.1/jar

**Comment by jbeemster** [comment]
Hey @rampatra apologies for the delay in getting back to you!  So it is now _more_ stable but this does creep in after a few days of runtime still (best uptime was 3 days straight).

Looking at it I think the best way to resolve this might be that IF the ping function starts throwing exceptions that we force reset the WebSocketConnection entirely.  Not sure if it is possible to force a hard reboot of the Bot class but that does appear to be what is needed to re-establish the connection properly.

Would a PR that allows [this function](https://github.com/rampatra/jbot/blob/master/jbot/src/main/java/me/ramswaroop/jbot/core/slack/Bot.java#L306-L315) to be re-called safely and that stores the Manager for replacement be a good idea?  Have not worked with Spring much so not sure if there is a better way to deal with this invalid WebSocketSession occurrence.

**Comment by rampatra** [comment]
Hey @jbeemster, no apologies needed. I too was on vacation for a long time and returned today. Btw, have you tried calling the `stop()` method on `WebSocketConnectionManager` and then `start()` again?

Whenever we see exceptions in Ping we can call `stop()` and then `start()`. What do you think about this?

**Comment by jbeemster** [comment]
Hey @rampatra so it looks like the [PR to solve the reconnect issue](https://github.com/rampatra/jbot/pull/138) might solve this one as well - would you mind pushing another RC up to Maven so I have a look at it?

**Comment by rampatra** [comment]
@jbeemster yes, sure. Will release and update here. Thanks, Josh.

**Comment by jbeemster** [comment]
My team will be so happy to not have to nudge me for a server reboot when it goes down!

**Comment by jbeemster** [comment]
Hey @rampatra was just wondering if you had an ETA on the next RC?

**Comment by rampatra** [comment]
@jbeemster hey, you should the next RC on maven within a couple of hours. The version is `jbot-4.1.2-rc.2`. Do let me know if this version solved the issue. If yes, I can go ahead and release the final version.

**Comment by jbeemster** [comment]
Initial tests with fragging my local network seem positive so far!  Have pushed it out to our staging environment now and will report back early next week if it survives!

**Comment by jbeemster** [comment]
@rampatra all signs to point so solved!  The bot has been running for the last 4 days without any downtime / need to be rebooted.

Might be prudent to leave it running for the rest of the week to be sure it is solved but can't see any new issues cropping up.

**Comment by rampatra** [comment]
That's great news @jbeemster. Keep me posted. Yes, definitely, let's leave it for the rest of the week and then conclude whether this has actually solved the issue.

**Comment by jbeemster** [comment]
@rampatra I consider this issue solved!  Consistent uptime through any weird network setup (even left it running on my laptop - disconnecting it from the network - putting it to sleep and all) and it always comes back to life.

**Comment by rampatra** [comment]
@jbeemster This is wonderful. Thanks a million for all the efforts you've put in to test it. I will release a final version soon. You can close this issue if you're satisfied.

**Comment by jbeemster** [comment]
No worries at all!
