### ISSUE TITLE
Payload doesn't have coordinates when got a response

### ISSUE THREAD

**Issue by Egorika** [rampatra/jbot#130]
### Describe the bug
When we got location attachment from user, payload with coordinates is null. 
Log from Jbot:
`Callback from fb: {"object":"page","entry":[{"id":"<id>","time":1540378107849,"messaging":[{"sender":{"id":"<id>"},"recipient":{"id":"<id>"},"timestamp":1540378107315,"message":{"mid":"<mid>","seq":1552,"attachments":[{"type":"location","payload":{}}]}}]}]}
`

So payload is `"payload":{}`

screenshot from ngrok:

![image](https://user-images.githubusercontent.com/1345170/47425872-4f473b00-d794-11e8-9e4b-258afe91684c.png)

### How to reproduce
Get location from user 

### Expected behavior
lat and long in the end.
`Callback from fb: {"object":"page","entry":[{"id":"<id>","time":1540377938652,"messaging":[{"sender":{"id":"<id>"},"recipient":{"id":"<id>"},"timestamp":1540377938191,"message":{"mid":"<mid>","seq":1548,"attachments":[{"type":"location","payload":{"coordinates":{"lat":"53.902496337891","long":"27.56148147583"}}}]}}]}]}` <--- lat and long

### Possible reason
@JsonProperty annotation cannot map nested objects like `coordinates.lat`. So solution could be:

```
    @JsonPropery("coordinates")
    private void setCoordinates(Map<String, String> coords) {
        this.coordinatesLat = coords.get("lat");
        this.coordinatesLong = coords.get("long");
    }
```

**Comment by rampatra** [comment]
Hi @Egorika, thanks for reporting the bug. Can you please share the fb api page link so that I can take a look at the type of the variables `lat` and `long`? I think it's `double`. Adding another `Coordinate` class in the fb models package should solve this issue.

**Comment by rampatra** [comment]
See this commit: https://github.com/rampatra/jbot/commit/d4f571bf1e1c46d42f158c677334c39c41222538

**Comment by Egorika** [comment]
> Can you please share the fb api page link so that I can take a look at the type of the variables `lat` and `long`? I think it's `double`.
I'm not sure what do you mean. Do you mean full response from fb like 
```
{
   "object":"page",
   "entry":[
      {
         "id":"<id>",
         "time":1540377938652,
         "messaging":[
            {
               "sender":{
                  "id":"<id>"
               },
               "recipient":{
                  "id":"<id>"
               },
               "timestamp":1540377938191,
               "message":{
                  "mid":"<mid>",
                  "seq":1548,
                  "attachments":[
                     {
                        "type":"location",
                        "payload":{
                           "coordinates":{
                              "lat":"53.902496337891",
                              "long":"27.56148147583"
                           }
                        }
                     }
                  ]
               }
            }
         ]
      }
   ]
}
```
or something else?

**Comment by rampatra** [comment]
Yes, exactly. I wanted this. So, it appears to be String. I will change the code and update. Thanks!

**Comment by Egorika** [comment]
Well, from ngrok I got this:
```
"coordinates":{
   "lat":53.902496337891,
   "long":27.56148147583
}
```
But in Jbot logs I got: 
```
"coordinates":{
   "lat":"53.902496337891",
   "long":"27.56148147583"
}
```
So it got to be Double I think, because logs parse object Callback back to json, as I know.

**Comment by Egorika** [comment]
Thank you !

**Comment by IslamSalah** [comment]
@rampatra I think the latest release `jbot-4.1.2-rc.1` still hasn't solved the issue. Could you please let me know when it will be fixed?
