### ISSUE TITLE
Can't clone the project

### ISSUE THREAD

**Issue by karenworld** [rampatra/jbot#134]
Hi,
I tried to clone your project but received the following error  
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Would appreciate if you could advise how to clone without the above error. tks.

**Comment by rampatra** [comment]
Try cloning with the https url and not ssh.
