### ISSUE TITLE
Bot status shows offline in Slack

### ISSUE THREAD

**Issue by abstract-karshit** [rampatra/jbot#49]
Hi,
I am currently running Jbot as part of a spring boot project, what I noticed is that after certain amount of time (could be inactivity, though I am not sure) bot shows offline in SLACK even though the application is running fine.
I had to restart my application to bring the bot online again.
Also, one thing I noticed in howdy botkit (running on ec2), that after sometime RTM has multiple instances running because of app trying to reconnect. https://github.com/howdyai/botkit/issues/750
Could these be related.
Also, any idea how to solve this issue of bot going offline.

**Comment by ramswaroop** [comment]
See these issues: https://github.com/ramswaroop/jbot/issues/43 and https://github.com/ramswaroop/jbot/issues/24

**Comment by abstract-karshit** [comment]
Thanks for replying. I went through the reported issues
I am not sending a large message so #24 is ruled out.
Regarding #43, currently I am running on local machine with a pretty stable internet connection but not sure if they could be related.
You suggested someone to echo from client ( #27 ), can you elaborate what exactly do we mean by this?

**Comment by mndominguez** [comment]
I'm having the same issue, and already checked #24 and #43. I'm running on a dedicated server so that's not an issue. Every couple of days I have to run the jar again because the bot shows as offline.

**Comment by ejwood79** [comment]
I'm having the same issue, and checked #24 and am running on paid AWS EC2 instances so I don't think #43 applies. I restarted the bot just now and will attempt to monitor its status somehow.

**Comment by ramswaroop** [comment]
Guys, I am using `supervisord` to manage the jbot java process and am not seeing any such issues. It would be worth trying it.

**Comment by rampatra** [comment]
This issue is fixed in this PR #106. Kindly used JBot version 4.1.0+ to circumvent this issue.
