### ISSUE TITLE
Making the jbot (on Slack) automatically post a message at a certain time every day

### ISSUE THREAD

**Issue by AtbTheGreat** [rampatra/jbot#60]
What EventType(s) do I need to use to make my JBot automatically post a message on Slack at a certain time every day? (eg. 6pm everyday)
If I'm not supposed to utilize an EventType to accomplish such a task, are there any other ways of doing so?

**Comment by ramswaroop** [comment]
You can create a TimerTask and have it post a message via the `reply()` method in whatever intervals you want.

**Comment by AtbTheGreat** [comment]
Thank you for the answer, however, it seems that I didn't word my initial question too well. For me to create a method that uses TimerTask to do such a task (always posting a message at a specific time every day even if none of the users are logged in), what should I set the parameter `events` to? Also, for my bot to work should the `next` parameter to any of the other methods be set equal to the name of the method I'm working on?

**Comment by dobrivoje** [comment]
How about to send a message to a group or a user ? Can you explain with code ?

**Comment by AtbTheGreat** [comment]
@dobrivoje Are you talking to me?

This is how I start my event conversation (by not using the `events` parameter but only starting the conversation whenever the user types in "report". My goal is to make my bot ask questions automatically at a certain time every day, and not only when the user types in a certain word):
```
@Controller(pattern="(report)", next="firstAnswer") // This establishes the method firstAnswer() as the method subsequent to init()
  public void init(WebSocketSession session, Event event) {
    if(rightTime(event.getUserId()) == true){ // Bot does nothing if it's not the right time/circumstances to ask questions
      initializeReaderAndWriter();
      reply(session, event, new Message(question1)); // Print out first question on Slack.
      startConversation(event, "firstAnswer");
    }
  }// end of method init()
```

This method is how I send each message (question) to the user and save each of the user's answers:
```
@Controller(next="secondAnswer") /* This establishes the method secondAnswer() as the method subsequent to firstAnswer()*/
  public void firstAnswer(WebSocketSession session, Event event) {
    if(writerIsOpen) {/* Pochemuchka will not output questions on Slack if the answer-saving feature answerWriter 
     * equals null or has already been closed.*/
      answerWriter.println(event.getText()); // Save the answer to the first question
      reply(session, event, new Message(question2)); /* Prints out the second question on Slack*/
      nextConversation(event); // Go to method secondAnswer(), as established in the @Controller()
    }
  } // end of method firstAnswer()
```

**Comment by l0uch3** [comment]
@AtbTheGreat Did you ever find out how to run scheduled message posts? I'm trying to figure out the same thing, but the event and session parameter of the reply method is holding me back.

**Comment by ajohnsonz** [comment]
@l0uch3 my understanding is that in your class that extends Bot, you can override the method `afterConnectionEstablished` which will give you the WebSocketSession and you can store this for later. Then when you want to send a message, you can use something like the following:

```
Message message = new Message("This is the text to send");
message.setType(EventType.MESSAGE.name().toLowerCase());
message.setChannel(channelId); // you need to lookup the channel id from channel name that you get in the RTM connect call
session.sendMessage(new TextMessage(message.toJSONString()));
```

Hope that helps!

**Comment by rampatra** [comment]
You can also have a look at `pingAtRegularIntervals()` method and `PingTask` in `Bot.java` under slack package. I added them recently which send a ping message to slack every 30 seconds to keep the web socket connection alive.

I am closing this question for now. Reopen it if you need further help.
