### ISSUE TITLE
Unexpected Status of SSLEngineResult after an unwrap() operation

### ISSUE THREAD

**Issue by trungie** [rampatra/jbot#97]
Bot becomes offline after this appears in the log message.

> 2018-05-17 22:40:33.706 DEBUG 5 --- [ient-SecureIO-1] me.ramswaroop.jbot.core.slack.Bot : WebSocket closed: StandardWebSocketSession[id=0, uri=null], Close Status: CloseStatus[code=1006, reason=Unexpected Status of SSLEngineResult after an unwrap() operation]

Service running on a dedicated AWS server.

**Comment by ramswaroop** [comment]
Any exceptions? Can you please paste the entire stacktrace?

**Comment by trungie** [comment]
There was not a stacktrace or exception. That was it.

**Comment by seckea01** [comment]
I'm seeing the same thing. Ubuntu 16.04 running on AWS, just like the OP:

> 18:48:13.591 [WebSocketClient-SecureIO-2] DEBUG o.s.w.s.h.LoggingWebSocketHandlerDecorator - StandardWebSocketSession[id=0, uri=null] closed with CloseStatus[code=1006, reason=Unexpected Status of SSLEngineResult after an unwrap() operation]
> 18:48:13.591 [WebSocketClient-SecureIO-2] DEBUG me.ramswaroop.jbot.core.slack.Bot - WebSocket closed: StandardWebSocketSession[id=0, uri=null], Close Status: CloseStatus[code=1006, reason=Unexpected Status of SSLEngineResult after an unwrap() operation]

...and on a non-AWS server, also running Ubuntu 16.04

> 23:45:20.921 [WebSocketClient-SecureIO-2] DEBUG o.s.w.s.h.LoggingWebSocketHandlerDecorator - StandardWebSocketSession[id=0, uri=null] closed with CloseStatus[code=1006, reason=Unexpected Status of SSLEngineResult after an unwrap() operation]
> 23:45:20.922 [WebSocketClient-SecureIO-2] DEBUG me.ramswaroop.jbot.core.slack.Bot - WebSocket closed: StandardWebSocketSession[id=0, uri=null], Close Status: CloseStatus[code=1006, reason=Unexpected Status of SSLEngineResult after an unwrap() operation]

No correlation with the preceding lines in the respective logfiles as far as I can see. No stacktrace.

**Comment by rampatra** [comment]
Can you try calling the `startWebSocketConnection()` method (added in this [PR](https://github.com/rampatra/jbot/pull/99)) when the connection closes?

**Comment by guikessa** [comment]
I have the same problema, after call startWebSocketConnection() is keeping.

**Comment by rampatra** [comment]
Can anyone tell me if you're getting this error while starting the bot?

I tried running JBot on a workspace having too many user accounts and I got this error. However, when I ran JBot where there were few user accounts, it runs fine.

**Comment by rampatra** [comment]
New version of JBot released which fixes web socket connection issues: https://github.com/rampatra/jbot/releases/tag/jbot-4.1.0

**Comment by rampatra** [comment]
Duplicate of #103.
