### ISSUE TITLE
How to get user info such as UserName using event object JBot for Facebook?  

### ISSUE THREAD

**Issue by OleksandrKharchenko** [rampatra/jbot#98]
Hello there!
Im trying to get user name and surname like this event.getSender().getFirstName() but always get a null pointer, is it possible to get this info or just messenger sends JSONObj without this data?

**Comment by rampatra** [comment]
Please go through https://api.slack.com/rtm and check for event types for which Slack sends user info.

**Comment by levindoneto** [comment]
Why is this closed if you (@rampatra ) gave the answer for Slack? He asked for Facebook, I'm also getting null pointers for Users from events. CAn you help us out?
![image](https://user-images.githubusercontent.com/12832687/44812936-e639b180-abae-11e8-974e-f617e0fdc803.png)

**Comment by levindoneto** [comment]
I've found a way to do so via GET request:
```
https://graph.facebook.com/v2.6/ID_USER?access_token=PAGE_ACCESS_TOKEN
```
Where ID_USER can be obtained via `event.getRecipient().getId()` and PAGE_ACCESS_TOKEN is the one used on application.properties :)

![image](https://user-images.githubusercontent.com/12832687/44814849-3f581400-abb4-11e8-8200-0f30ff8660b4.png)

**Comment by rampatra** [comment]
Great. I also opened a PR https://github.com/rampatra/jbot/pull/119/files which includes a service to fetch user details. You can add more methods to this service for each and every call.

**Comment by rampatra** [comment]
Would be great if you guys can review the PR before I merge.
